### ISSUE TITLE
[BUG] release 2.1.2.4 Configs are quite broken

### ISSUE THREAD

**Issue by ellensp** [MarlinFirmware/Configurations#1065]
### Bug Description

Configuration_adv.h has "`#elif SDSUPPORT`"  this should be  "`#elif HAS_MEDIA`"

obsolete define added "`#define EXPERIMENTAL_SCURVE     // Allow S-Curve Acceleration to be used with LA.`"

Wrong versions used
Has "`#define CONFIGURATION_H_VERSION 02010203`"
Should be "`#define CONFIGURATION_H_VERSION 02010204`"

Has "`#define CONFIGURATION_ADV_H_VERSION 02010203`"
Should be "`#define CONFIGURATION_ADV_H_VERSION 02010204`"

### Configuration Files

All release 2.1.2.4 examples configs have multiple issues

### Steps to Reproduce

1. Download Marlin 2.1.2.4
2. add any example config
3. Buid
4. It errors out

**Expected behavior:**

It should build

**Actual behavior:**

It does not build

**Comment by thisiskeithb** [comment]
I found some other minor issues:

"`// Add 'P' parameter to set percentage done, otherwise use Marlin's estimate`" is in some configs, but not others. It should be "`// Add 'P' parameter to set percentage done`"

"`// Add 'R' parameter to set remaining time, otherwise use Marlin's estimate`" is in some configs, but not others. It should be "`// Add 'R' parameter to set remaining time`"

"`// G-code to run on Stop Print (e.g., "G28XY" or "G27")`" is in some configs, but not others. It should be "`// G-code to run on SD Abort Print (e.g., "G28XY" or "G27")`"

**Comment by thisiskeithb** [comment]
I submitted patch, but I know it'll automatically close when `2.1.2.4` is force-pushed :)

- https://github.com/MarlinFirmware/Configurations/pull/1066

Diff: [Fix 2.1.2.4 typos.diff.zip](https://github.com/user-attachments/files/15875844/Fix.2.1.2.4.typos.diff.zip)
Patch: [Fix 2.1.2.4 typos.patch.zip](https://github.com/user-attachments/files/15875843/Fix.2.1.2.4.typos.patch.zip)

**Comment by matthew-yates** [comment]
I changed this:

```
#if BOTH(SDSUPPORT, DIRECT_STEPPING)
  #define BLOCK_BUFFER_SIZE  8
#elif SDSUPPORT
  #define BLOCK_BUFFER_SIZE 16
#else
  #define BLOCK_BUFFER_SIZE 16
#endif
```

to this:

```
#if BOTH(SDSUPPORT, DIRECT_STEPPING)
  #define BLOCK_BUFFER_SIZE  8
#else
  #define BLOCK_BUFFER_SIZE 16
#endif
```

I don't see why the extra "elif" is needed.

**Comment by thisiskeithb** [comment]
https://github.com/MarlinFirmware/Configurations/pull/1066 has been merged / https://github.com/MarlinFirmware/Configurations/tree/release-2.1.2.4 has been fixed.
