### ISSUE TITLE
[FR] Feedback on closed PRs

### ISSUE THREAD

**Issue by thisiskeithb** [MarlinFirmware/Configurations#29]
### Description

Can we get feedback on PRs when they're closed & not merged? PR #28 for BigTreeTech's MK3S BTT002 config was closed without feedback and is not in any of the branches, so I'm not sure what needs to be corrected before submitting another PR.

**Comment by thinkyhead** [comment]
Sometimes a PR can get closed due to its target branch getting force-pushed, and no one might notice for many days.

To make submitting new configurations easier I've now made our working import branch public. The `import-2.0.x` branch should be used as your starting point, and then submit your PR to that branch.

```
git fetch upstream
git checkout upstream/import-2.0.x -b my_new_configs_PR
```
