### ISSUE TITLE
[BUG] (short description)

### ISSUE THREAD

**Issue by fumanschuh** [MarlinFirmware/Configurations#502]
Sapphire Plus MKS UI 
When i define the MKS UI the touchscreen is disabled.

**Comment by ellensp** [comment]
as fas as I am aware the MKS UI is only for TFT's with an encoder. 

eg <img src="https://ae01.alicdn.com/kf/Hcb6cbd33bf404d3fa6f56bd78fea8770l/Makerbase-MKS-TS35-3-5-touch-screen-for-MKS-Robin-Nano-E3P-SGen-L.jpg">

**Comment by thisiskeithb** [comment]
> as fas as I am aware the MKS UI is only for TFT's with an encoder.

No, it works on MKS' other TFTs as well.

**Comment by thisiskeithb** [comment]
Interestingly, the author of the config specifically disables `TOUCH_SCREEN` if you enable the special/config-specific flag `SAPPHIRE_PLUS_MKS_UI`, so it's intentional:

https://github.com/MarlinFirmware/Configurations/blob/dd4de330913ae7e416a66a33e4b76a5fe8ece807/config/examples/Two%20Trees/Sapphire%20Plus/Sapphire%20Plus%20V2/Configuration.h#L2609-L2611

Outside of this printer's specific config, MKS's UI works fine with `MKS_ROBIN_TFT35`.

**Comment by thinkyhead** [comment]
Fill out a bug report at the main project.
