### ISSUE TITLE
[BUG] (SD Issue)

### ISSUE THREAD

**Issue by Enzo-Enz** [MarlinFirmware/Configurations#652]
Marlin 2.0.9.3 doesn't show the file on the sd card 
I use BTT SKR PRO V1.2 and generic delta configuration

**Comment by thisiskeithb** [comment]
Without providing the config exactly as modified, I’m going to guess that you forgot to enable `SDSUPPORT` and `SDCARD_CONNECTION` since those are disabled by default.


<hr>

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by Enzo-Enz** [comment]
I had enabled SDSUPPORT and SD_check_and_retry but when I click on "print from media" It doesn't show the file

**Comment by Enzo-Enz** [comment]
![6d2547e0-bef6-4514-8706-7709d02d16fc](https://user-images.githubusercontent.com/75531691/148692083-ffa7df08-eb28-441c-9432-5f96e6fda2ae.jpg)
![8bddc964-8a8f-4b13-8cc2-3731e6e95ac9](https://user-images.githubusercontent.com/75531691/148692087-4d4119ff-49ab-457d-959a-2b47efe408d9.jpg)
![69c6ba0e-ecf4-44ad-a398-3eabd216474b](https://user-images.githubusercontent.com/75531691/148692093-ab5efc08-e9bc-48ed-985c-b36dca831c22.jpg)
