### ISSUE TITLE
Anycubic i3 Trigorilla Z2 Stepper on E1 "No E stepper plug left for Z2!"

### ISSUE THREAD

**Issue by Tamperold** [MarlinFirmware/Configurations#89]
Hello,
I have a problem which has been dealt with here before. I can't get the second Z-Stepper motor to the E1 on the Trigorilla_13 board. Every time I get the error: exit status 1
#error "No E stepper plug left for Z2!"

Under "Configuration_adv.h" I have entered "#define NUM_Z_STEPPER_DRIVERS 2".
Then I deleted the // in "#define Z_STEPPER_AUTO_ALIGN" (according to info from another post).

Under "Configuration.h" I deleted the // "#define Z2_DRIVER_TYPE A4988".

Nevertheless I can't get it to run. In the E1 all pins are entered.

Thanks for the help.

**Comment by thinkyhead** [comment]
You should post an issue to the Marlin project and fill out the complete template including a ZIP of your configuration files and any other files you've modified. Someone can then try compiling it and see why it is failing to build. Be sure to test with the latest `bugfix-2.0.x` code beforehand in case your issue is already fixed.
